Repository WhaleDone22/WhaleDone-Client, pull requests merged in 2022-03, with the labels that each got.

#32 Feat/#25
  assets/ic-add-family.png
  assets/ic-arrow-right.png
  assets/ic-bell.png
  assets/ic-daily.png
  assets/ic-distance-line.png
  assets/ic-distance-line2.png
  assets/ic-health.png
  assets/ic-profile-image-edit.png
  assets/ic-relationship.png
  assets/ic-tmi.png
  assets/ic-user-circle.png
  assets/ic-work.png
  assets/image-profile-default.png
  assets/image-profile-ex1.png
  assets/image-profile-ex2.png
  assets/logo-whaledone.png
  assets/mypage-line.png
  assets/profile-image-default.png
  package.json
  presentation/components/ProgressBar.tsx
  presentation/screens/Main/Home.tsx
  presentation/screens/Main/Map.tsx
  presentation/screens/Main/MapDetail.tsx
  presentation/screens/Main/Mypage.tsx
  presentation/screens/Signup/GroupCodeInput.tsx
  presentation/screens/index.tsx
Labels: feature 🎄

#33 오디오 야매 ui 구현
  App.tsx
  assets/ic-close.png
  assets/ic-record-pause.png
  assets/ic-record-send.png
  assets/ic-record-start.png
  babel.config.js
  presentation/components/AudioRecorder.tsx
  presentation/screens/Main/Feed.tsx
  yarn.lock
Labels: feature 🎄

#36 fix: 맵화면 UI 수정
  .eslintrc.js
  infrastructures/types/NavigationStackParams.ts
  presentation/components/AudioPlayer.tsx
  presentation/components/AudioRecorder.tsx
  presentation/components/FeedItem.tsx
  presentation/components/ProgressBar.tsx
  presentation/components/ReactionItem.tsx
  presentation/screens/Main/Feed.tsx
  presentation/screens/Main/Home.tsx
  presentation/screens/Main/Map.tsx
  presentation/screens/Main/MapDetail.tsx
  presentation/screens/Main/Mypage.tsx
  presentation/screens/Signup/BottomSheet.tsx
  presentation/screens/Signup/BottomSheetHeader.tsx
  presentation/screens/Signup/Greet.tsx
  presentation/screens/Signup/GroupCodeInput.tsx
  presentation/screens/Signup/GroupCodeShare.tsx
  presentation/screens/Signup/NicknameInput.tsx
Labels: fix ☔️, feature 🎄

#39 💅style: 메인 carousel UI 이슈
  .eslintrc.js
  package-lock.json
  package.json
  presentation/screens/Main/EditProfile.tsx
  presentation/screens/Main/Home.tsx
  presentation/screens/Main/Mypage.tsx
  presentation/screens/Signup/GroupCodeInput.tsx
  presentation/screens/Signup/GroupCodeShare.tsx
  presentation/screens/Signup/Login.tsx
  tsconfig.json
  yarn-error.log
  yarn.lock
Labels: fix ☔️, feature 🎄

#41 ✨feat: 마이페이지 U수정 UI 구현
  presentation/screens/Main/EditProfile.tsx
  presentation/screens/Main/Mypage.tsx
Labels: feature 🎄

#50 회원가입 앞부분 QA 반영
  assets/ic-checkbox-checked-false.png
  assets/ic-checkbox-checked-true.png
  infrastructures/data/serviceActiveCountries.json
  infrastructures/types/NavigationStackParams.ts
  presentation/screens/Signup/EmailInput.tsx
  presentation/screens/Signup/Login.tsx
  presentation/screens/Signup/NicknameInput.tsx
  presentation/screens/Signup/PasswordFind.tsx
  presentation/screens/Signup/PasswordInput.tsx
  presentation/screens/Signup/PhoneAuth.tsx
  presentation/screens/Signup/PhoneInput.tsx
  presentation/screens/index.tsx
Labels: fix ☔️, feature 🎄

#51 여러가지 QA 반영하기
  assets/ic-close-terms.png
  assets/ic-emoji.png
  assets/ic-text.png
  infrastructures/types/NavigationStackParams.ts
  package.json
  presentation/screens/Main/Home.tsx
  presentation/screens/Main/Record.tsx
  presentation/screens/Signup/PhoneInput.tsx
  yarn.lock
Labels: fix ☔️, feature 🎄, chore 💪

#58 feat: 메인페이지 질문 carousel api 연동
  infrastructures/types/NavigationStackParams.ts
  presentation/screens/Main/Home.tsx
  presentation/screens/Main/Map.tsx
  presentation/screens/Main/MapDetail.tsx
  presentation/screens/Main/Record.tsx
Labels: feature 🎄

#59 회원가입 및 가족 초대 구현
  infrastructures/api/remote/base.ts
  infrastructures/types/NavigationStackParams.ts
  presentation/screens/Main/Map.tsx
  presentation/screens/Signup/EmailInput.tsx
  presentation/screens/Signup/GroupCodeInput.tsx
  presentation/screens/Signup/GroupCodeShare.tsx
  presentation/screens/Signup/Login.tsx
  presentation/screens/Signup/NicknameInput.tsx
  presentation/screens/Signup/PasswordInput.tsx
  presentation/screens/Signup/PhoneAuth.tsx
  presentation/screens/Signup/PhoneInput.tsx
Labels: feature 🎄

#60 소통함, 일상공유 API 연결
  .eslintrc.js
  infrastructures/api/feed.ts
  infrastructures/api/index.ts
  infrastructures/api/mock/feed.data.ts
  infrastructures/api/mock/feed.ts
  infrastructures/api/remote/feed.ts
  infrastructures/data/reactionEmoji.json
  infrastructures/types/@types/index.d.ts
  infrastructures/types/feed.ts
  infrastructures/utils/images.ts
  package.json
  presentation/components/PhotoSelectorModal.tsx
  presentation/screens/Main/Feed.tsx
  presentation/screens/Main/Record.tsx
  yarn.lock
Labels: feature 🎄

#62 마지막 달리기
  assets/img-empty-alarm.png
  infrastructures/api/feed.ts
  infrastructures/api/index.ts
  infrastructures/api/mock/feed.ts
  infrastructures/api/remote/feed.ts
  infrastructures/api/remote/notice.ts
  infrastructures/types/NavigationStackParams.ts
  infrastructures/types/feed.ts
  infrastructures/utils/images.ts
  presentation/components/AudioRecorder.tsx
  presentation/components/FeedItem.tsx
  presentation/components/FeedsPerDay.tsx
  presentation/components/PhotoSelectorModal.tsx
  presentation/screens/Main/Feed.tsx
  presentation/screens/Main/Notice.tsx
  presentation/screens/Main/Record.tsx
Labels: fix ☔️, feature 🎄

#64 Entry Point 제대로 하기
  infrastructures/types/NavigationStackParams.ts
  presentation/screens/Signup/Greet.tsx
  presentation/screens/index.tsx
Labels: fix ☔️, feature 🎄
