Repository WhaleDone22/WhaleDone-Client, pull requests merged in 2022-04, with the labels that each got.

#76 마이페이지, 프로필 수정 API 연결하기
  .eslintrc.js
  presentation/screens/AppInit/Onboarding.tsx
  presentation/screens/Main/EditProfile.tsx
  presentation/screens/Main/Mypage.tsx
  presentation/screens/Signup/Greet.tsx
  presentation/screens/Signup/GroupCodeInput.tsx
  presentation/screens/Signup/GroupCodeShare.tsx
  presentation/screens/Signup/Login.tsx
  presentation/screens/Signup/NicknameInput.tsx
  presentation/screens/index.tsx
Labels: fix ☔️, feature 🎄

#77 오디오 UI 개선
  presentation/components/AudioPlayer.tsx
  presentation/components/ReactionItem.tsx
Labels: fix ☔️, feature 🎄

#78 마음거리 기능 구현
  infrastructures/types/NavigationStackParams.ts
  infrastructures/utils/circles.ts
  infrastructures/utils/distances.ts
  presentation/components/ProgressBar.tsx
  presentation/screens/Main/Home.tsx
  presentation/screens/Main/Map.tsx
  presentation/screens/Main/MapDetail.tsx
  presentation/screens/Signup/Greet.tsx
  presentation/screens/Signup/GroupCodeInput.tsx
  presentation/screens/Signup/PhoneInput.tsx
Labels: feature 🎄

#85 ✨ feat: 마음거리 가족 채널명 수정
  presentation/screens/Main/Map.tsx
Labels: feature 🎄

#87 데모데이 D-1 의논했던 기능 마무리
  infrastructures/api/family.ts
  infrastructures/api/index.ts
  infrastructures/api/remote/family.ts
  infrastructures/types/NavigationStackParams.ts
  presentation/screens/Main/GroupCodeReissue.tsx
  presentation/screens/Main/Map.tsx
  presentation/screens/index.tsx
Labels: fix ☔️, feature 🎄

#89 다른 나라에 있어도 태극기가 나타나는 버그 수정, 마음거리 디자인 반영
  infrastructures/api/remote/feed.ts
  presentation/screens/Main/Map.tsx
Labels: fix ☔️
